package org.eclipse.osgi.technology.incubator.opentelemetry.weaver.scr;

import org.objectweb.asm.AnnotationVisitor;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.commons.AdviceAdapter;

/**
 * ASM {@link AdviceAdapter} that detects DS lifecycle annotations on methods
 * and constructors, wrapping annotated methods with OpenTelemetry instrumentation
 * by delegating to {@link ScrInstrumentationHelper}.
 * <p>
 * The generated bytecode is equivalent to:
 * <pre>
 * Object[] ctx = ScrInstrumentationHelper.onLifecycleEnter(className, methodName, action);
 * try {
 *     // original method body
 * } catch (Throwable t) {
 *     ScrInstrumentationHelper.onLifecycleError(ctx, t);
 *     throw t;
 * } finally {
 *     ScrInstrumentationHelper.onLifecycleExit(ctx);
 * }
 * </pre>
 */
class ScrMethodVisitor extends AdviceAdapter {

    private static final String ACTIVATE_DESC = "Lorg/osgi/service/component/annotations/Activate;";
    private static final String DEACTIVATE_DESC = "Lorg/osgi/service/component/annotations/Deactivate;";
    private static final String MODIFIED_DESC = "Lorg/osgi/service/component/annotations/Modified;";

    private static final String HELPER =
            "org/eclipse/osgi/technology/incubator/opentelemetry/weaver/scr/ScrInstrumentationHelper";

    private final String className;
    private final String methodName;
    private final boolean isConstructor;
    private String action;
    private Runnable transformCallback;
    private int contextLocal;

    ScrMethodVisitor(MethodVisitor mv, int access, String name,
            String descriptor, String className) {
        super(Opcodes.ASM9, mv, access, name, descriptor);
        this.className = className;
        this.methodName = name;
        this.isConstructor = "<init>".equals(name);
    }

    void setTransformCallback(Runnable callback) {
        this.transformCallback = callback;
    }

    @Override
    public AnnotationVisitor visitAnnotation(String descriptor, boolean visible) {
        switch (descriptor) {
            case ACTIVATE_DESC -> action = isConstructor ? "constructor" : "activate";
            case DEACTIVATE_DESC -> action = "deactivate";
            case MODIFIED_DESC -> action = "modified";
        }
        return super.visitAnnotation(descriptor, visible);
    }

    @Override
    protected void onMethodEnter() {
        if (action == null) {
            return;
        }
        if (transformCallback != null) {
            transformCallback.run();
        }

        contextLocal = newLocal(Type.getType("[Ljava/lang/Object;"));

        visitLdcInsn(className.replace('/', '.'));
        visitLdcInsn(isConstructor ? "<init>" : methodName);
        visitLdcInsn(action);
        visitMethodInsn(Opcodes.INVOKESTATIC, HELPER, "onLifecycleEnter",
                "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Object;",
                false);
        storeLocal(contextLocal);
    }

    @Override
    protected void onMethodExit(int opcode) {
        if (action == null) {
            return;
        }
        if (opcode == ATHROW) {
            dup();
            int exLocal = newLocal(Type.getType("Ljava/lang/Throwable;"));
            storeLocal(exLocal);
            loadLocal(contextLocal);
            loadLocal(exLocal);
            visitMethodInsn(Opcodes.INVOKESTATIC, HELPER, "onLifecycleError",
                    "([Ljava/lang/Object;Ljava/lang/Throwable;)V", false);
        }
        loadLocal(contextLocal);
        visitMethodInsn(Opcodes.INVOKESTATIC, HELPER, "onLifecycleExit",
                "([Ljava/lang/Object;)V", false);
    }
}
